### ISSUE TITLE
No data/bop

### ISSUE THREAD

**Issue by Eddieeee-Liu** [YoungSean/NIDS-Net#6]
Thanks for your great work. But maybe the released code is not complete? I canot test your model for bop challenge

**Comment by YoungSean** [comment]
After getting the prediction results, you could submit via [BOP website](https://bop.felk.cvut.cz/login/?next=/sub_upload/) to evaluate BOP datasets.

**Comment by Eddieeee-Liu** [comment]
I know, but have you check the repo? I think there is something wrong with your repo, I can not run your inference code successfully

**Comment by Eddieeee-Liu** [comment]
1. your repo missing the config data/bop (I copy it from the sam6d, and modify the paths)
2. you didn't provide the data arrangment of your bop inference code (I have try my best to debug step by step)

**Comment by YoungSean** [comment]
I mainly followed [CNOS](https://github.com/nv-nguyen/cnos) instead of Sam6D. We do not need the config data/bop from SAM6D.

By the way, what is the specific problem?

**Comment by YoungSean** [comment]
Thank you very much. Let us add the file. We are using the data/bop from CNOS. We mainly follow [CNOS](https://github.com/nv-nguyen/cnos) for segmentation.

**Comment by Eddieeee-Liu** [comment]
Thanks~

**Comment by Eddieeee-Liu** [comment]
BTW, I wander how I can generate descriptors_pbr for my own dataset?

**Comment by YoungSean** [comment]
To generate descriptors_pbr,

There are two ways:
1. Following CNOS 
 First, write a dataloader for your dataset, which can get images and their masks. Use a loop to compute the visual features like [code here](https://github.com/YoungSean/NIDS-Net/blob/main/src/model/detector.py#L229)

2. Use our dataset class and generate foreground feature averaging in this [script](https://github.com/YoungSean/NIDS-Net/blob/main/get_object_features_via_FFA.py#L189). Our approach may be more straightforward.

**Comment by Eddieeee-Liu** [comment]
Thanks
