### ISSUE TITLE
Machin specification for evaluation of BOP benchmark

### ISSUE THREAD

**Issue by MosyMosy** [YoungSean/NIDS-Net#7]
Hello, thank you for the great work. I am trying to compare the methods on the BOP benchmark from the time perspective. It would be very beneficial if you could shape the machine specification you have used to evaluate the BOP benchmark's datasets. Thank you very much

**Comment by YoungSean** [comment]
The experiments are conducted on an RTX A5000 GPU (24GB CUDA Memory).

**Comment by MosyMosy** [comment]
Thank you very much @YoungSean.

**Comment by MosyMosy** [comment]
Done
